#TicTacToe settings
#Thu Apr 30 11:51:08 EDT 2026
timerEnabled=true
winCondition=3
boardSize=3
timerSeconds=20
musicEnabled=false
aiDifficulty=MEDIUM
timerExpiryAction=RANDOM_MOVE
volumePercent=63
themeMode=OCEAN
gameMode=HUMAN_VS_AI
soundEnabled=true
