#TicTacToe settings
#Thu May 07 12:05:10 EDT 2026
aiDifficulty=MEDIUM
boardSize=3
gameMode=HUMAN_VS_AI
musicEnabled=false
soundEnabled=true
themeMode=DARK
timerEnabled=true
timerExpiryAction=RANDOM_MOVE
timerSeconds=20
volumePercent=63
winCondition=3
